on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Spotless check
        run: ./gradlew spotlessCheck
      - name: Build with Gradle
        run: ./gradlew build
      - name: Check with Gradle
        run: ./gradlew check
  android_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          disable-animations: true
          script: ./gradlew connectedAndroidTest
