on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Spotless check
        run: ./gradlew spotlessCheck
      - name: Unit tests
        run: ./gradlew test
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          script: ./gradlew connectedAndroidTest
